name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build_windows_amd64:
    name: Build for Windows 64-bit
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.13.7'
      - name: Setup MSYS
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
      - name: Build artifacts
        env:
          PATH: ''
        run: make GOOS=windows GOARCH=amd64 setup
      - name: Hash artifacts
        run: sha256sum dist/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buster-client-windows-amd64
          path: dist/

  build_linux_amd64:
    name: Build for Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.13.7'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev xorg-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip
      - name: Build artifacts
        run: make GOOS=linux GOARCH=amd64 setup
      - name: Hash artifacts
        run: sha256sum dist/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buster-client-linux-amd64
          path: dist/

  build_linux_arm64:
    name: Build for Linux Arm
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.13.7'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev xorg-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip
      - name: Build artifacts
        run: make GOOS=linux GOARCH=arm64 setup
      - name: Hash artifacts
        run: sha256sum dist/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buster-client-linux-arm64
          path: dist/

  release:
    name: Release on GitHub
    runs-on: ubuntu-24.04
    needs:
      - build_windows_amd64
      - build_linux_amd64
      - build_linux_arm64
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Get release version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true
      - name: Hash artifacts
        run: sha256sum dist/*
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: |
            Learn more about this release from the [changelog](https://github.com/dessant/buster-client/blob/master/CHANGELOG.md#changelog).
          files: dist/*
          draft: true
